### ISSUE TITLE
ERROR: dev-vcs/gitkraken-9999-r9999::cynede failed (prepare phase):  unpack: ./data.tar.gz does not exist

### ISSUE THREAD

**Issue by Gooberpatrol66** [Heather/gentoo-cynede#13]
[build.log](https://github.com/Heather/gentoo-cynede/files/2019362/build.log)

**Comment by mpkh** [comment]
oh :(

**Comment by mpkh** [comment]
@Gooberpatrol66 gitg is better than gitkraken imho

**Comment by mpkh** [comment]
fixed

**Comment by mpkh** [comment]
most likely it needs net-misc/curl with CURL_SSL set to gnutls

**Comment by Gooberpatrol66** [comment]
Cool, thanks for the tip
