### ISSUE TITLE
dev-qt/qt-creator-4.2.1 version bump

### ISSUE THREAD

**Issue by kamikaze** [Heather/gentoo-cynede#4]
4.2.0-rc1 fails to build. Is it possible to get 4.2.1?

**Comment by kamikaze** [comment]
Nevermind... looks liks I'm fooled )

https://bugreports.qt.io/browse/QTCREATORBUG/fixforversion/16210/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel

**Comment by mpkh** [comment]
you can track it here https://github.com/qtproject/qt-creator/releases
