### ISSUE TITLE
Can't emerge qt-creator

### ISSUE THREAD

**Issue by csanyipal** [Heather/gentoo-cynede#5]
Hi,
I set up my Gentoo linux for the cynede layman.
Then try to emerge dev-qt/qt-creator but get error message:

> In file included from qbsproject.h:30:0,
>                  from qbsbuildconfiguration.cpp:32:
> qbsnodes.h:116:58: error: ‘ArtifactData’ in namespace ‘qbs’ does not name a type
>      static ProjectExplorer::FileType fileType(const qbs::ArtifactData &artifact);
>                                                           ^
> Makefile:1151: recipe for target '.obj/release-shared/qbsbuildconfiguration.o' failed
> make[3]: *** [.obj/release-shared/qbsbuildconfiguration.o] Error 1
> make[3]: Leaving directory '/var/tmp/portage/dev-qt/qt-creator-4.2.0/work/qt-creator-opensource-src-4.2.0/src/plugins/qbsprojectmanager'
> Makefile:1246: recipe for target 'sub-qbsprojectmanager-make_first' failed
> make[2]: *** [sub-qbsprojectmanager-make_first] Error 2
> make[2]: Leaving directory '/var/tmp/portage/dev-qt/qt-creator-4.2.0/work/qt-creator-opensource-src-4.2.0/src/plugins'
> Makefile:133: recipe for target 'sub-plugins-make_first-ordered' failed
> make[1]: *** [sub-plugins-make_first-ordered] Error 2
> make[1]: Leaving directory '/var/tmp/portage/dev-qt/qt-creator-4.2.0/work/qt-creator-opensource-src-4.2.0/src'
> Makefile:43: recipe for target 'sub-src-make_first-ordered' failed
> make: *** [sub-src-make_first-ordered] Error 2
>  * ERROR: dev-qt/qt-creator-4.2.0::cynede failed (compile phase):
>  *   emake failed

How can I solve this problem?
Best, from Pal

**Comment by mpkh** [comment]
very strange error

however I've removed it from overlay now: https://github.com/Heather/gentoo-cynede/commit/8e6813906dcb3a18453efdce4a2983358fa0cb4e

it was there because tree was slow, now you can just use version from main tree.

**Comment by csanyipal** [comment]
OK. I am now installing from the main tree of gentoo.
