### ISSUE TITLE
redigest viber

### ISSUE THREAD

**Issue by bes-internal** [Heather/gentoo-cynede#6]
I ask at freenode #gentoo:

> How to write live(9999) ebuild with SRC_URI=..../data.gz (no version) that cause wrong checksum in manifest (1) if mainstream was updated and dosn't download at all because data.gz already exist in distfiles (2) ?

But all the answers were that it was impossible to change the behavior of portage.
So it is necessary to check the new version with some periodicity in order to update the manifest with new checksums

At 2017-03-20 viber in this overlay has (digest) version for 6.0.1
But latest 6.5.1

**Comment by mpkh** [comment]
yes, it's very weak that they don't have versions archives
ideally - to store those deb files somewhere
I've fixed it for now but only until the next update :)
